import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Exo } from "next/font/google";

import SmoothAOS from "./_components/SmoothAOS";
import { VideoProvider } from "../_context/VideoContext";

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <Navbar />
        <SmoothAOS />
        <VideoProvider>{children}</VideoProvider>
      </body>
    </html>
  );
}
